### PR TITLE
Update deployments reference to `balancer-deployments`

### LINKED ISSUE #83: Change `deployments/` references to new `balancer-deployments` repository
We are moving the [deployments package](https://github.com/balancer/balancer-v2-monorepo/tree/master/pkg/deployments) in the monorepo to a [standalone repository](https://github.com/balancer/balancer-deployments).

In short, every reference to `<monorepo>/pkg/deployments` should now move to the deployments repository root.

For example, https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/deployments should move to https://github.com/balancer/balancer-deployments/blob/master. Same applies to raw URLs and any other reference. The internal structure of the deployment tasks stays the same.

The existing deployments in the monorepo have already been ported to the new deployments repository, and we'll be no longer updating the monorepo with newer deployment tasks and updates. The deployments package contents will be removed from the monorepo once there are no more dangling references to it.

### PR DESCRIPTION
**Pull request by jubeira**
Update references to `deployments/` package in the monorepo to the new [balancer-deployments repository](https://github.com/balancer/balancer-deployments).

Closes #83.

### CODE REVIEW

**Comment by jubeira** [comment]
See https://github.com/balancer/balancer-v2-monorepo/pull/2504 for reference.

**Comment by EndymionJkb** [comment]
Noting that we also have deployments to new networks: Avalanche, BSC, Sepolia, zkEVM

**Review by Tritium-VLK — APPROVED** [review]
Thanks! Looks good.  Was working on some of the same but missed some.  Also doing a bit of cleanup around multichain and getting zkevm and  avax loaded.  This thing is almost at the point where we will never need to touch it :)

**Review by Tritium-VLK — CHANGES_REQUESTED** [review]
Actually hold off, maybe better I merge your changes into my other work and have you do a review.

**Comment by Tritium-VLK** [comment]
See #86

**Comment by Tritium-VLK** [comment]
Ahh I see.  Bit of a merge conflict here. Basically @mikemcdonald merge this first and then overwrite all the scripts and stuff in the .github folder with #86.  The rest of the changes in 86 can also overwrite @jubeira's changes, but it doesn't really matter either way as everything will be rebuilt on the next actions run (can do a manual run).

There are a few other changes to other parts of the docs here that should be included.

**Review by mikemcdonald — APPROVED** [review]

**Pull request merged**
