### PR TITLE
Updated Gov Process and more changes to multisig section.

### PR DESCRIPTION
**Pull request by Tritium-VLK**

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
@mikemcdonald the preview build action somehow failed.  Is there a way you can rerun it so I can share with some others?

**Comment by mikemcdonald** [comment]
Here's the build error:

```
Error: [vite]: Rollup failed to resolve import "images/govProcess.png" from "/opt/buildhome/repo/docs/.vuepress/.temp/pages/concepts/governance/process.html.vue".
```

Once that's fixed and pushed it should build fine. If you run into this in the future, you should be able to see any issues locally by running `npm run build`

**Comment by mikemcdonald** [comment]
Thanks for all the help with the content - this is great. It looks like there are lots of random newlines mid-sentence throughout the text in the PR, can you double check? Could maybe be a setting in your code editor.

Ex: https://github.com/balancer-labs/docs/pull/12/files#diff-d70d42596792029bf7e342e6a43181718e742cf5824d8df2c0894e2ff82b3e28R28-R29

**Comment by Tritium-VLK** [comment]
@mikemcdonald 

Yeah I think it's formatting things not to overrun a certain line length with md format.  How do you prefer long lines?  Do you need an entire paragraph on one line with 2 lfs after, or just linefeeds at sentence breaks and/or less ugly places?

**Comment by mikemcdonald** [comment]
Yea preferably only at the end of paragraphs. Not sure what editor you use but you should be able to set it to wrap text to the window size so it will read across multiple lines but not change the underlying formatting

**Review by mikemcdonald — APPROVED** [review]
I'm gonna go ahead and merge this since the PR is getting pretty large, but feel free to open up another for any further updates/fixes

**Pull request merged**
