### PR TITLE
TsDocs from the SDK

### PR DESCRIPTION
**Pull request by gmbronco**
First step to sync code comments with the docs.
Not yet exposed in the navigation, accessible under /api (temporary default name).

Good to have them browsable, easier to see what we need to do to clean them up.

Starting with BalancerSDK class, our main entry point, which doesn't have any comments or examples.

### CODE REVIEW

**Comment by gmbronco** [comment]
Modules preview: https://tsdocs-sdk.balancer-docs.pages.dev/api/modules.html

**Comment by gmbronco** [comment]
I think I got our docs from comments to the point where we can replace existing SDK section with auto-generated docs. What do you think about it?

For auto-generation I added vuepress-typedoc plugin which gives the best results compared to api-extractor. So far it's a manual task, but can be automated once we get comfortable with the content.

It's a start, next steps I'm thinking about changing few things in the swaps module to make naming and flow consistent with joins/exists.

**Comment by mikemcdonald** [comment]
Cool, I'll take a look through tomorrow

**Comment by mikemcdonald** [comment]
Overall, I find it really hard to cut through the noise of the auto-generated docs to find informative details on how the SDK works. The existing SDK section has a high level page which introduces the reader to a topic, walks through, and provides tips, gotchas, and other details.

Ex: a page like https://tsdocs-sdk.balancer-docs.pages.dev/sdk/reference/interfaces/Pool.html or https://tsdocs-sdk.balancer-docs.pages.dev/sdk/reference/enums/BalancerErrorCode.html I think are relatively pointless.

I would remove the Enums, Interfaces, and Modules sections entirely. The Classes section can be useful, but should have more explanations about what each class is and how it can be used. Also, the full list of parameters can be greatly condensed by removing `Implementation of` (which I don't think is particularly useful?) and moving the defined in link into an arrow on the header or after the content.

**Comment by gmbronco** [comment]
I'm with you. Classes section is very helpful in getting a quick insight what's there, but besides that it's too noisy. I really like how viem docs look like. Seems like they just maintain them manually. I'll look into making it more readable.

**Pull request closed without merging**
